config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task.id)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task.id)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.7/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
 <%= simple_form_for(task) do |f| %>
  <%= f.input :title, class: 'form-control' %>
  <%= f.input :details, class: 'form-control' %>
  <% if task.persisted? %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <% end %>
  <br>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container text-center">
  <h1>Edit your less than perfect task</h1>
  <%= render "form", task: @task %>
  <br>
  <%= link_to "Back to all tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="container text-center">
  <h1>All my tasks</h1>
  <ul class="list-group border mx 400px">
  <% @tasks.each do |task| %>
  <% if task.completed  %>
    <li><i class="fas fa-check-square"></i><%= link_to task.title, task_path(task.id) %>
  <% else %>
    <li><i class="fas fa-square"></i><%= link_to task.title, task_path(task.id) %>
  <% end %>

   <%= link_to '',
                task_path(task.id),
                method: :delete,
                data: { confirm: "Delete #{task.title}?" },
                class: "far fa-trash-alt" %></li>
  <% end %>
  </ul>

  <%= link_to '', tasks_new_path, class: "fas fa-plus-square" %>
</div>

app/views/tasks/new.html.erb
<div class="container text-center">
  <h1>Create your new perfect task</h1>
  <%= render "form", task: @task %>
  <br>
  <%= link_to "Back to all tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<div class="container text-center">
  <h1><%= @task.title %></h1>
  <p><%= @task.details %></p>
  <%= link_to "", edit_task_path, class: "far fa-edit" %>
  <br>
  <%= link_to "Back to all tasks", tasks_path %>
</div>